package com.sakura.tm.common.entity.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductDetailOrgExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public ProductDetailOrgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_org
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public ProductDetailOrgExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_org
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public ProductDetailOrgExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductDescIsNull() {
            addCriterion("product_desc is null");
            return (Criteria) this;
        }

        public Criteria andProductDescIsNotNull() {
            addCriterion("product_desc is not null");
            return (Criteria) this;
        }

        public Criteria andProductDescEqualTo(String value) {
            addCriterion("product_desc =", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotEqualTo(String value) {
            addCriterion("product_desc <>", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescGreaterThan(String value) {
            addCriterion("product_desc >", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescGreaterThanOrEqualTo(String value) {
            addCriterion("product_desc >=", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLessThan(String value) {
            addCriterion("product_desc <", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLessThanOrEqualTo(String value) {
            addCriterion("product_desc <=", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLike(String value) {
            addCriterion("product_desc like", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotLike(String value) {
            addCriterion("product_desc not like", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescIn(List<String> values) {
            addCriterion("product_desc in", values, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotIn(List<String> values) {
            addCriterion("product_desc not in", values, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescBetween(String value1, String value2) {
            addCriterion("product_desc between", value1, value2, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotBetween(String value1, String value2) {
            addCriterion("product_desc not between", value1, value2, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlIsNull() {
            addCriterion("product_img_url is null");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlIsNotNull() {
            addCriterion("product_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlEqualTo(String value) {
            addCriterion("product_img_url =", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlNotEqualTo(String value) {
            addCriterion("product_img_url <>", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlGreaterThan(String value) {
            addCriterion("product_img_url >", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("product_img_url >=", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlLessThan(String value) {
            addCriterion("product_img_url <", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlLessThanOrEqualTo(String value) {
            addCriterion("product_img_url <=", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlLike(String value) {
            addCriterion("product_img_url like", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlNotLike(String value) {
            addCriterion("product_img_url not like", value, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlIn(List<String> values) {
            addCriterion("product_img_url in", values, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlNotIn(List<String> values) {
            addCriterion("product_img_url not in", values, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlBetween(String value1, String value2) {
            addCriterion("product_img_url between", value1, value2, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductImgUrlNotBetween(String value1, String value2) {
            addCriterion("product_img_url not between", value1, value2, "productImgUrl");
            return (Criteria) this;
        }

        public Criteria andProductAddressIsNull() {
            addCriterion("product_address is null");
            return (Criteria) this;
        }

        public Criteria andProductAddressIsNotNull() {
            addCriterion("product_address is not null");
            return (Criteria) this;
        }

        public Criteria andProductAddressEqualTo(String value) {
            addCriterion("product_address =", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressNotEqualTo(String value) {
            addCriterion("product_address <>", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressGreaterThan(String value) {
            addCriterion("product_address >", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressGreaterThanOrEqualTo(String value) {
            addCriterion("product_address >=", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressLessThan(String value) {
            addCriterion("product_address <", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressLessThanOrEqualTo(String value) {
            addCriterion("product_address <=", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressLike(String value) {
            addCriterion("product_address like", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressNotLike(String value) {
            addCriterion("product_address not like", value, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressIn(List<String> values) {
            addCriterion("product_address in", values, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressNotIn(List<String> values) {
            addCriterion("product_address not in", values, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressBetween(String value1, String value2) {
            addCriterion("product_address between", value1, value2, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductAddressNotBetween(String value1, String value2) {
            addCriterion("product_address not between", value1, value2, "productAddress");
            return (Criteria) this;
        }

        public Criteria andProductParameterIsNull() {
            addCriterion("product_parameter is null");
            return (Criteria) this;
        }

        public Criteria andProductParameterIsNotNull() {
            addCriterion("product_parameter is not null");
            return (Criteria) this;
        }

        public Criteria andProductParameterEqualTo(String value) {
            addCriterion("product_parameter =", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterNotEqualTo(String value) {
            addCriterion("product_parameter <>", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterGreaterThan(String value) {
            addCriterion("product_parameter >", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterGreaterThanOrEqualTo(String value) {
            addCriterion("product_parameter >=", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterLessThan(String value) {
            addCriterion("product_parameter <", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterLessThanOrEqualTo(String value) {
            addCriterion("product_parameter <=", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterLike(String value) {
            addCriterion("product_parameter like", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterNotLike(String value) {
            addCriterion("product_parameter not like", value, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterIn(List<String> values) {
            addCriterion("product_parameter in", values, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterNotIn(List<String> values) {
            addCriterion("product_parameter not in", values, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterBetween(String value1, String value2) {
            addCriterion("product_parameter between", value1, value2, "productParameter");
            return (Criteria) this;
        }

        public Criteria andProductParameterNotBetween(String value1, String value2) {
            addCriterion("product_parameter not between", value1, value2, "productParameter");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_detail_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private ProductDetailOrgExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_detail_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(ProductDetailOrgExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_detail_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public ProductDetailOrgExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_detail_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table product_detail_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table product_detail_org
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}