package com.sakura.tm.common.entity;

import java.math.BigDecimal;
import java.util.Date;


public class SysBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.id
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.bank_no
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.banK_card
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.bank_card_password
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private String bankCardPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.user_id
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.bank_money
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private BigDecimal bankMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.bank_card_type
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private Integer bankCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.create_time
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.update_time
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bank
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public SysBank(Integer id, String bankNo, String bankCard, String bankCardPassword, Integer userId, BigDecimal bankMoney, Integer bankCardType, Date createTime, Date updateTime) {
        this.id = id;
        this.bankNo = bankNo;
        this.bankCard = bankCard;
        this.bankCardPassword = bankCardPassword;
        this.userId = userId;
        this.bankMoney = bankMoney;
        this.bankCardType = bankCardType;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bank
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public SysBank() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.id
     *
     * @return the value of sys_bank.id
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.id
     *
     * @param id the value for sys_bank.id
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.bank_no
     *
     * @return the value of sys_bank.bank_no
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.bank_no
     *
     * @param bankNo the value for sys_bank.bank_no
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.banK_card
     *
     * @return the value of sys_bank.banK_card
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.banK_card
     *
     * @param bankCard the value for sys_bank.banK_card
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.bank_card_password
     *
     * @return the value of sys_bank.bank_card_password
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public String getBankCardPassword() {
        return bankCardPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.bank_card_password
     *
     * @param bankCardPassword the value for sys_bank.bank_card_password
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setBankCardPassword(String bankCardPassword) {
        this.bankCardPassword = bankCardPassword == null ? null : bankCardPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.user_id
     *
     * @return the value of sys_bank.user_id
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.user_id
     *
     * @param userId the value for sys_bank.user_id
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.bank_money
     *
     * @return the value of sys_bank.bank_money
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public BigDecimal getBankMoney() {
        return bankMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.bank_money
     *
     * @param bankMoney the value for sys_bank.bank_money
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setBankMoney(BigDecimal bankMoney) {
        this.bankMoney = bankMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.bank_card_type
     *
     * @return the value of sys_bank.bank_card_type
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public Integer getBankCardType() {
        return bankCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.bank_card_type
     *
     * @param bankCardType the value for sys_bank.bank_card_type
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setBankCardType(Integer bankCardType) {
        this.bankCardType = bankCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.create_time
     *
     * @return the value of sys_bank.create_time
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.create_time
     *
     * @param createTime the value for sys_bank.create_time
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.update_time
     *
     * @return the value of sys_bank.update_time
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.update_time
     *
     * @param updateTime the value for sys_bank.update_time
     *
     * @mbggenerated Wed May 27 11:20:51 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}