package com.sakura.tm.common.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 用户表
 * user_digita_org
 * @author 李七夜
 * @date 2020-06-02 14:36:33
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "user_digita_org")
public class UserDigitaOrg implements Serializable {
    /**
     */
    private Integer userId;

    /**
     * 用户名
     */
    private String userName;

    /**
     * 密码
     */
    private String password;

    /**
     */
    private String pwdSlt;

    /**
     * 手机号
     */
    private String phone;

    /**
     * 生日
     */
    private Date birthday;

    /**
     * 性别,0:女,1:男
     */
    private Integer sex;

    /**
     * 用户状态,-1:禁用,1:启用
     */
    private Integer state;

    /**
     * 是否是实名认证,-1:未实名认证,1:已经实名认证
     */
    private Integer isRealNameAuthentication;

    /**
     * 身份证号
     */
    private String idCard;

    /**
     * 注册地址
     */
    private String zone;

    /**
     */
    private Date createTime;

    /**
     */
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table user_digita_org
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        userId("user_id"),
        userName("user_name"),
        password("password"),
        pwdSlt("pwd_slt"),
        phone("phone"),
        birthday("birthday"),
        sex("sex"),
        state("state"),
        isRealNameAuthentication("is_real_name_authentication"),
        idCard("id_card"),
        zone("zone"),
        createTime("create_time"),
        updateTime("update_time");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_digita_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_digita_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_digita_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_digita_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_digita_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_digita_org
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}